frr defaults traditional
hostname r100
no ipv6 forwarding
!
password zebra
enable password zebra
!
interface eth1
 ip address 123.1.1.100/24
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 15
exit
!
interface eth2
 ip address 10.10.100.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth3
 ip address 10.11.100.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth4
 ip address 10.13.100.2/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth5
 ip address 10.100.111.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth6
 ip address 10.100.110.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface eth7
 ip address 10.100.101.1/30
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit
!
interface lo
 ip address 123.123.100.100/32
 ip ospf 1 area 0
exit
!
router ospf 1
 ospf router-id 123.123.100.100
exit
!
router bgp 65000
 bgp router-id 123.123.100.100
 no bgp default ipv4-unicast
 neighbor LEAVES peer-group
 neighbor LEAVES remote-as 65000
 neighbor LEAVES update-source lo
 neighbor LEAVES timers 3 9
 neighbor 123.14.14.14 peer-group LEAVES
 neighbor 123.15.15.15 peer-group LEAVES
 neighbor 123.123.30.30 peer-group LEAVES
 neighbor 123.123.31.31 peer-group LEAVES
 neighbor 123.123.101.101 remote-as 65000
 neighbor 123.123.101.101 update-source lo
 !
 address-family l2vpn evpn
  neighbor LEAVES activate
  neighbor LEAVES route-reflector-client
  neighbor LEAVES soft-reconfiguration inbound
  neighbor 123.123.101.101 activate
  neighbor 123.123.101.101 soft-reconfiguration inbound
 exit-address-family
 !
 bmp targets TOPOLOGRAPH
  bmp connect 172.31.30.100 port 11019 min-retry 100 max-retry 10000
  bmp monitor l2vpn evpn pre-policy
  bmp monitor l2vpn evpn post-policy
 exit
exit
!
