frr defaults traditional
hostname r131
no ipv6 forwarding
!
password zebra
enable password zebra
!
interface eth1
 ip address 10.30.131.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface eth2
 ip address 10.31.131.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface eth3
 ip address 10.130.131.2/30
 ip ospf 1 area 1
 ip ospf cost 10
exit
!
interface lo
 ip address 123.123.31.31/32
 ip ospf 1 area 1
exit
!
router ospf 1
 ospf router-id 123.123.31.31
exit
!
interface bond0
 evpn mh es-id 1
 evpn mh es-sys-mac 44:38:39:ff:00:01
exit
!
router bgp 65000
 bgp router-id 123.123.31.31
 no bgp default ipv4-unicast
 neighbor RRS peer-group
 neighbor RRS remote-as 65000
 neighbor RRS update-source lo
 neighbor RRS timers 3 9
 neighbor 123.123.100.100 peer-group RRS
 !
 address-family l2vpn evpn
  neighbor RRS activate
  advertise-all-vni
 exit-address-family
exit
!
vrf tenant1
 vni 5000
exit-vrf
!
router bgp 65000 vrf tenant1
 bgp router-id 123.123.31.31
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 address-family l2vpn evpn
  advertise ipv4 unicast
 exit-address-family
exit
!
